### ISSUE TITLE
Closing dev console in electron application is changing the workspace color

### ISSUE THREAD

**Issue by sylwiabr** [luna/ide#239] opened 2020-03-06 14:59 UTC
### General Summary

When I am closing the developers tools in electron application the workspace colour is changing to darker grey.
### Steps to Reproduce

open electron app with `--dev` option
close developers tools
### Expected Result

just the right panel will be closed
### Actual Result

[close-dev-tools.tar.gz](https://github.com/luna/ide/files/4298907/close-dev-tools.tar.gz)

**Comment by wdanilo** [comment] 2020-03-06 16:54
This is an expected behavior. Electron is not able to show correct bg color when dev console is open. The dark grey you see is not the final color of course, but it is the valid one now. Not going to be fixed now. I'll leave it open – maybe someone will have a hacky idea how to fix it. I will be revisiting this topic as well.

**Comment by wdanilo** [comment] 2020-03-16 06:18
@sylwiabr is this dark color the same one as when you open the app without `--dev` ?

**Comment by sylwiabr** [comment] 2020-03-16 08:41
yes, it is

**Comment by wdanilo** [comment] 2020-03-16 08:42
Then it is not a bug. Vibrance (transparent blurry background) is not working with dev tools opened. This is an electron bug that would probably never be solved. Closing.

**Closed by wdanilo** 2020-03-16 08:42 UTC
Labels: Category: IDE, Priority: Medium, Status: Wontfix, Type: Bug
